export const BROWSERANGEDATA = [
  {
    name: "Dining",
    image: "dining.png",
  },
  {
    name: "Living",
    image: "living.png",
  },
  {
    name: "Bedroom",
    image: "bedroom.png",
  },
];

export const PRODUCTS = [
  {
    _id: "6559c018a7e755f9e0b5c0fa",
    name: "Maimz Sofa",
    price: 700,
    originPrice: 882,
    quantity: 60,
    quantitySale: 15,
    shortDesc: "Sofa",
    fullDesc: {
      data: {
        brief:
          "The Maimz sofa is mid-century revival done to perfection. Linear and minimalistic, the beautifully edited profile has all the retro elements you love, like sheltering arms, bolster pillows and tapered splayed legs. So casually cool, the caramel faux leather upholstery brings the look right into the present.",
        atrb1: "Corner-blocked frame",
        atrb2: "Reversible back and seat cushions",
        atrb3: "High-resiliency foam cushions wrapped in thick poly fiber",
        atrb4: "Faux leather upholstery",
        atrb5: "Attached arm bolster pillows",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 90.00 - 38.00 - 38.00",
        atrb1: "Arm height: 32.00'",
        atrb2: "Distance between arms: 69.00'",
        atrb3: "Leg height: 6.00'",
        atrb4: "Minimum width of doorway for delivery: 32.00'",
        atrb5: "Seat depth: 20.00'",
      },
    },
    type: ["Livingroom"],
    images: [
      "/Livingroom/maimz_Sofa/img1.webp",
      "/Livingroom/maimz_Sofa/img2.webp",
      "/Livingroom/maimz_Sofa/img3.webp",
      "/Livingroom/maimz_Sofa/img4.webp",
    ],
    rating: 4.8,
    discount: "-26%",
    id: "6559c018a7e755f9e0b5c0fa",
  },
  {
    _id: "6559c018a7e755f9e0b5c0fb",
    name: "Altari Sofa",
    price: 400,
    originPrice: 532,
    quantity: 30,
    quantitySale: 8,
    shortDesc: "Sofa",
    fullDesc: {
      data: {
        brief:
          "If style is the question, then the Altari sofa is the answer. Sporting clean lines and sleek track arms, the decidedly contemporary profile is enhanced with plump cushioning and a chenille-feel upholstery, so pleasing to the touch. Sure to play well with so many color schemes, this sofa in slate gray includes a pair of understated floral pattern pillows for fashionably fresh appeal.",
        atrb1: "Corner-blocked frame",
        atrb2: "Attached back and loose seat cushions",
        atrb3: "High-resiliency foam cushions wrapped in thick poly fiber",
        atrb4: "2 decorative pillows included",
        atrb5: "Pillows with soft polyfill",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 85.00 - 37.00 - 38.00",
        atrb1: "Arm height: 26.00'",
        atrb2: "Distance between arms: 70.00'",
        atrb3: "Leg height: 3.00'",
        atrb4: "Minimum width of doorway for delivery: 32.00'",
        atrb5: "Seat depth: 20.00'",
      },
    },
    type: ["Livingroom"],
    images: [
      "/Livingroom/altari_Sofa/img1.webp",
      "/Livingroom/altari_Sofa/img2.webp",
      "/Livingroom/altari_Sofa/img3.webp",
      "/Livingroom/altari_Sofa/img4.webp",
    ],
    rating: 4.5,
    discount: "-33%",
    id: "6559c018a7e755f9e0b5c0fb",
  },
  {
    _id: "6559c018a7e755f9e0b5c0fc",
    name: "Calion Sofa",
    price: 450,
    originPrice: 612,
    quantity: 80,
    quantitySale: 8,
    shortDesc: "Sofa",
    fullDesc: {
      data: {
        brief:
          "In the chicest shade of gray, Calion sofa’s linen-weave upholstery complements so many color schemes and aesthetics. Flared arms, prominent welting and flamestitch-print pillows add just enough panache to this sweet and simple sofa. Supportive seat cushions make for one comfortable landing pad.",
        atrb1: "Corner-blocked frame",
        atrb2: "Attached back and loose seat cushions",
        atrb3: "High-resiliency foam cushions wrapped in thick poly fiber",
        atrb4: "4 decorative pillows included",
        atrb5: "Polyester upholstery and pillows with soft polyfill",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 87.00 - 38.00 - 38.00",
        atrb1: "Seat depth: 22.00'",
        atrb2: "Seat height: 19.00'",
        atrb3: "Distance between arms: 69.00'",
        atrb4: "Top of cushion to top of back: 18.00'",
        atrb5: "Arm height: 26.00'",
      },
    },
    type: ["Livingroom"],
    images: [
      "/Livingroom/calion_Sofa/img1.webp",
      "/Livingroom/calion_Sofa/img2.webp",
      "/Livingroom/calion_Sofa/img3.webp",
      "/Livingroom/calion_Sofa/img4.webp",
    ],
    rating: 4.5,
    discount: "-36%",
    id: "6559c018a7e755f9e0b5c0fc",
  },
  {
    _id: "6559c018a7e755f9e0b5c0fd",
    name: "Jarreau Sofa Chaise Sleeper",
    price: 500,
    originPrice: 600,
    quantity: 72,
    quantitySale: 3,
    shortDesc: "Sofa",
    fullDesc: {
      data: {
        brief:
          "Small space living is easier than ever with the Jarreau sofa chaise sleeper. The soft cushions and oversized pillow backs are sure to be a comfortable seating treat. Sporting sleek arms and friendly apartment sizing, this sleeper makes a fashionable first impression, and is quick to convert into a sleeper with the included pullout cushion. Great to accommodate guests for an overnight stay.",
        atrb1: "Loose cushions",
        atrb2: "High-resiliency foam cushions wrapped in thick poly fiber",
        atrb3: "Polyester upholstery",
        atrb4:
          "Includes a pullout cushion that sits atop a supportive steel frame",
        atrb5: "Exposed feet with faux wood finish",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 83.00 - 36.00 - 53.00",
        atrb1: "Seat width: 78.13'",
        atrb2: "Seat height: 18.25'",
        atrb3: "Seat depth: 20.63'",
        atrb4: "Arm height: 22.00'",
        atrb5: "Top of cushion to top of back: 18.250'",
      },
    },
    type: ["Livingroom"],
    images: [
      "/Livingroom/jarreau_Sofa_Chaise_Sleeper/img1.webp",
      "/Livingroom/jarreau_Sofa_Chaise_Sleeper/img2.webp",
      "/Livingroom/jarreau_Sofa_Chaise_Sleeper/img3.webp",
      "/Livingroom/jarreau_Sofa_Chaise_Sleeper/img4.webp",
    ],
    rating: 4.5,
    discount: "-20%",
    id: "6559c018a7e755f9e0b5c0fd",
  },
  {
    _id: "6559c018a7e755f9e0b5c0fe",
    name: "Dolante Queen Upholstered Bed with Square Button Tufting",
    price: 250,
    originPrice: 275,
    quantity: 15,
    quantitySale: 4,
    shortDesc: "Queen Upholstered Bed",
    fullDesc: {
      data: {
        brief:
          "Serenity now. This queen upholstered bed is sure to awaken a love for modern platform styling with a softer side. Plush to the touch and so easy on the eyes, a pale beige fabric hugs the bed—from the chic headboard with square button tufting, to the low footboard and side rails, emanating the calming mood you long for in the bedroom. Mattress and foundation/box spring sold separately.",
        atrb1: "Includes headboard, footboard and rails",
        atrb2: "Engineered wood frame",
        atrb3: "Polyester upholstery on headboard, footboard and rails",
        atrb4: "Square button tufting on headboard",
        atrb5: "Foundation/box spring required",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 66.75 -  60.75 - 86.50",
        atrb1: "Panel to floor: 22.25'",
        atrb2: "Rail width: 61.88'",
        atrb3: "Rail to floor: 3.38'",
        atrb4: "Assembled queen upholstered bed Width : 66.75'",
        atrb5: "Assembled queen upholstered bed Depth : 86.50'",
      },
    },
    type: ["Bedroom"],
    images: [
      "/Bedroom/dolante_Queen_Upholstered_Bed/img1.webp",
      "/Bedroom/dolante_Queen_Upholstered_Bed/img2.webp",
      "/Bedroom/dolante_Queen_Upholstered_Bed/img3.webp",
      "/Bedroom/dolante_Queen_Upholstered_Bed/img4.webp",
    ],
    rating: 4.5,
    discount: "-10%",
    id: "6559c018a7e755f9e0b5c0fe",
  },
  {
    _id: "6559c018a7e755f9e0b5c106",
    name: "Galtbury 72' Bookcase",
    price: 160,
    originPrice: 192,
    quantity: 58,
    quantitySale: 5,
    shortDesc: "Bookcase",
    fullDesc: {
      data: {
        brief:
          "Put a personal touch into your space with the Galtbury on-trend bookcase, perfect for showing off framed photos, books and favorite objects. Defined by its distinctive mix of materials, this piece pairs an open metal frame in a bronze-tone finish with 5 fixed distressed wooden shelves for a look that’s right at home in an industrial, modern farmhouse or rustic setting.",
        atrb1: "Metal, veneer and engineered wood",
        atrb2: "Estimated Assembly Time: 30 Minutes",
        atrb3: "Metal frame with bronze-tone finish",
        atrb4: "5 fixed shelves",
        atrb5: "Assembly required",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 36.13 -  72.38 -  12.25",
        atrb1: "Opening (5) Width : 36.13'",
        atrb2: "Opening (5) Depth : 10.13'",
        atrb3: "Opening (5) Height : 11.88'",
        atrb4: "Lift top opening Width : 20.25'",
        atrb5: "Small desk Depth : 15.75'",
      },
    },
    type: ["Livingroom", "Bedroom"],
    images: [
      "/Bookcases/galtbury_72_Bookcase/img1.webp",
      "/Bookcases/galtbury_72_Bookcase/img2.webp",
      "/Bookcases/galtbury_72_Bookcase/img3.webp",
      "/Bookcases/galtbury_72_Bookcase/img4.webp",
    ],
    rating: 4.9,
    discount: "-20%",
    id: "6559c018a7e755f9e0b5c106",
  },
  {
    _id: "6559c018a7e755f9e0b5c108",
    name: "Arlenbry 55' L-Shaped Home Office Desk with Shelf",
    price: 320,
    originPrice: 352,
    quantity: 37,
    quantitySale: 7,
    shortDesc: "Home Office Desk",
    fullDesc: {
      data: {
        brief:
          "Clean-lined and contemporary—but far from stark—the Arlenbry L-desk with hutch is a fresh style awakening. Sleek scale makes it a natural fit for smaller spaces. Effortlessly combining modern farmhouse design with urban attitude, the replicated weathered oak grain plays perfectly with the chic yet earthy aesthetic.",
        atrb1: "Made of decorative laminate, engineered wood and metal",
        atrb2: "Replicated weathered oak grain",
        atrb3:
          "L-desk includes desk with drawer and shelf, hutch with display shelf and return",
        atrb4: "Convenient cubby for additional storage",
        atrb5: "Metal frame with black finish",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 55.00 -  38.02 -  55.25",
        atrb1: "Large desk Width : 54.00'",
        atrb2: "Large desk Depth : 19.75'",
        atrb3: "Large desk Height : 30.00'",
        atrb4: "Small desk Width : 55.25'",
        atrb5: "Small desk Depth : 15.75'",
      },
    },
    type: ["Livingroom", "Bedroom", "Diningroom"],
    images: [
      "/Desks/arlenbry_5_Desk/img1.webp",
      "/Desks/arlenbry_5_Desk/img2.webp",
      "/Desks/arlenbry_5_Desk/img3.webp",
      "/Desks/arlenbry_5_Desk/img4.webp",
    ],
    rating: 4.9,
    discount: "-10%",
    id: "6559c018a7e755f9e0b5c108",
  },
  {
    _id: "6559c018a7e755f9e0b5c10a",
    name: "Shawburn 54' Home Office Desk",
    price: 180,
    originPrice: 198,
    quantity: 27,
    quantitySale: 4,
    shortDesc: "Home Office Desk",
    fullDesc: {
      data: {
        brief:
          "Add an air of quaint productivity to your work-from-home or schoolwork setup. The Shawburn home office desk fits right in with modern farmhouse aesthetics. Design highlights include a two-tone finish and warm pewter-tone hardware. Looking to bring delightful homespun charm to your everyday routine? This desk’s light and fresh vibes are bound to please.",
        atrb1:
          "Made with engineered wood (MDF/particleboard/plywood) and decorative laminate for the right balance of affordability and durability",
        atrb2: "Whitewash replicated worn through paint",
        atrb3:
          "Top with rustic gray planked replicated oak grain with authentic touch",
        atrb4:
          "Decorative laminate replicates natural or man-made material surfaces with consistent color, pattern and texture",
        atrb5: "Pewter-tone pulls",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 54.00 -  28.75 -  19.00",
        atrb1: "Weight: 82.00 lbs (37.19 kgs)",
        atrb2: "Lift top extended height: 41.38'",
        atrb3: "Side drawer interior (lined) (2) Height : 2.00'",
        atrb4: "Small desk Width : 55.25'",
        atrb5: "Lift top opening (2) Depth : 23.00'",
      },
    },
    type: ["Livingroom", "Bedroom", "Diningroom"],
    images: [
      "/Desks/shawburn_54_Desk/img1.webp",
      "/Desks/shawburn_54_Desk/img2.webp",
      "/Desks/shawburn_54_Desk/img3.webp",
      "/Desks/shawburn_54_Desk/img4.webp",
    ],
    rating: 4.7,
    discount: "-10%",
    id: "6559c018a7e755f9e0b5c10a",
  },
  {
    _id: "6559c018a7e755f9e0b5c101",
    name: "Alisdair Queen Sleigh Bed",
    price: 250,
    originPrice: 312.5,
    quantity: 37,
    quantitySale: 7,
    shortDesc: "Queen Sleigh Bed",
    fullDesc: {
      data: {
        brief:
          "The Alisdair queen sleigh bed is the epitome of traditional decor. Louis Philippe-style moulding dates back to the mid-19th century when furnishings were lavish yet somewhat simple. Deep finish brings warmth and elegance into the space. Mattress and foundation/box spring sold separately.",
        atrb1: "Includes headboard/footboard and rails",
        atrb2: "Made of veneers, wood and engineered wood",
        atrb3: "Foundation/box spring required",
        atrb4: "Mattress available, sold separately",
        atrb5: "Assembly required",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 63.00 -  47.00 -  85.00",
        atrb1: "Queen sleigh footboard Width : 62.50'",
        atrb2: "Queen sleigh footboard Depth : 5.75'",
        atrb3: "Queen sleigh footboard Height : 26.50'",
        atrb4: "Queen sleigh headboard Width : 62.50'",
        atrb5: "Queen sleigh headboard Depth : 6.50'",
      },
    },
    type: ["Bedroom"],
    images: [
      "/Bedroom/alisdair_Queen_Sleigh_Bed/img1.webp",
      "/Bedroom/alisdair_Queen_Sleigh_Bed/img2.webp",
      "/Bedroom/alisdair_Queen_Sleigh_Bed/img3.webp",
      "/Bedroom/alisdair_Queen_Sleigh_Bed/img4.webp",
    ],
    rating: 4.9,
    discount: "-25%",
    id: "6559c018a7e755f9e0b5c101",
  },
  {
    _id: "6559c018a7e755f9e0b5c102",
    name: "Lakeleigh Queen Panel Bed",
    price: 700,
    originPrice: 805,
    quantity: 47,
    quantitySale: 1,
    shortDesc: "Queen Panel Bed",
    fullDesc: {
      data: {
        brief:
          "Opposites attract. The Lakeleigh panel bed opens our eyes to how casually rustic styling and an industrial hip vibe make for one happy marriage. Elements that beautify the chunky, linear profile include through-tenon styling, replicated planking and faux barn door hardware loaded with charm. What’s even more surprising: how such a high-quality designer piece can be so attractively priced. Mattress and foundation/box spring available, sold separately.",
        atrb1: "Made of acacia wood, engineered wood, and veneers",
        atrb2: "Includes headboard, footboard and rails",
        atrb3: "Assembly required",
        atrb4: "Foundation/box spring required, sold separately",
        atrb5: "Mattress available, sold separately",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 68.00 -  61.00 -  88.00",
        atrb1: "Queen panel rail (2) Width : 63.00'",
        atrb2: "Queen panel rail (2) Depth : 80.50'",
        atrb3: "Queen panel rail (2) Height : 14.70'",
        atrb4: "Panel to floor: 22.25'",
        atrb5: "Queen panel footboard Width : 68.00'",
      },
    },
    type: ["Bedroom"],
    images: [
      "/Bedroom/lakeleigh_Queen_Panel_Bed/img1.webp",
      "/Bedroom/lakeleigh_Queen_Panel_Bed/img2.webp",
      "/Bedroom/lakeleigh_Queen_Panel_Bed/img3.webp",
      "/Bedroom/lakeleigh_Queen_Panel_Bed/img4.webp",
    ],
    rating: 4.9,
    discount: "-15%",
    id: "6559c018a7e755f9e0b5c102",
  },
  {
    _id: "6559c018a7e755f9e0b5c104",
    name: "Beckincreek Large Bookcase with 5 Shelves",
    price: 400,
    originPrice: 440,
    quantity: 20,
    quantitySale: 7,
    shortDesc: "Bookcase with 5 Shelves",
    fullDesc: {
      data: {
        brief:
          "Make a style statement with the Beckincreek large bookcase. Its traditional design is updated with an on trend vintage black finish. The bookcase's five shelves add up to a well-organized workspace.",
        atrb1: "Made with solid wood frames, elm veneer and MDF substrate",
        atrb2: "Vintage black finish",
        atrb3: "5 shelves; 4 are adjustable",
        atrb4: "Assembly required",
        atrb5: "Estimated Assembly Time: 15 Minutes",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 34.25 -  75.00 -  12.00",
        atrb1: "Opening #1 Width : 39.25'",
        atrb2: "Opening #1 Depth : 10.00'",
        atrb3: "Opening #1 Height : 33.00'",
        atrb4: "Adjustable shelf (4) Width : 32.50'",
        atrb5: "Adjustable shelf (4) Depth : 10.00'",
      },
    },
    type: ["Livingroom", "Bedroom"],
    images: [
      "/Bookcases/beckincreek_Large_Bookcase/img1.webp",
      "/Bookcases/beckincreek_Large_Bookcase/img2.webp",
      "/Bookcases/beckincreek_Large_Bookcase/img3.webp",
      "/Bookcases/beckincreek_Large_Bookcase/img4.webp",
    ],
    rating: 4.9,
    discount: "-10%",
    id: "6559c018a7e755f9e0b5c104",
  },
  {
    _id: "6559c018a7e755f9e0b5c105",
    name: "Carynhurst 75' Bookcase with 4 Shelves",
    price: 370,
    originPrice: 518,
    quantity: 15,
    quantitySale: 2,
    shortDesc: "Bookcase with 4 Shelves",
    fullDesc: {
      data: {
        brief:
          "Looking for a fresh approach to modern farmhouse living? The Carynhurst bookcase works on so many levels. Clean-lined profile with crossbuck back never goes out of fashion. Whitewash finish is a mastery in subtle sophistication.",
        atrb1: "Made of pine veneers, pine wood and engineered wood",
        atrb2: "Distressed whitewash finish",
        atrb3: "4 shelves; 2 of which are adjustable",
        atrb4: "Assembly required",
        atrb5: "Estimated Assembly Time: 45 Minutes",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 37.63 -  78.13 -  16.00",
        atrb1: "Opening #1 Width : 29.50'",
        atrb2: "Opening #1 Depth : 13.00'",
        atrb3: "Opening #1 Height : 49.50'",
        atrb4: "Adjustable shelf (4) Width : 34.05'",
        atrb5: "Adjustable shelf (4) Depth : 12.75'",
      },
    },
    type: ["Livingroom", "Bedroom"],
    images: [
      "/Bookcases/carynhurst_75_Bookcase/img1.webp",
      "/Bookcases/carynhurst_75_Bookcase/img2.webp",
      "/Bookcases/carynhurst_75_Bookcase/img3.webp",
      "/Bookcases/carynhurst_75_Bookcase/img4.webp",
    ],
    rating: 4.9,
    discount: "-40%",
    id: "6559c018a7e755f9e0b5c105",
  },
  {
    _id: "6559c018a7e755f9e0b5c10b",
    name: "Havalance 62' Home Office Lift Top Desk with USB Charging",
    price: 450,
    originPrice: 562.5,
    quantity: 35,
    quantitySale: 7,
    shortDesc: "Home Office Desk",
    fullDesc: {
      data: {
        brief:
          "Have your fill of modern farmhouse style with the Havalance desk. A vintage white base pairs with a weathered gray top for an utterly charming home office workstation. The built-in lift top allows you to adjust your workspace to suit your needs, while storage drawers keep office essentials on hand. Simply stunning, the desk also keeps up with your high-tech lifestyle with the help of USB charging ports.",
        atrb1: "Made with pine wood, veneer and engineered woody",
        atrb2: "Distressed weathered gray top; vintage white base",
        atrb3: "Lift-top design",
        atrb4: "Small concealed tray under lift top",
        atrb5: "2 storage drawers",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 62.38 -  31.13 -  27.25",
        atrb1: "Lift top extended depth: 39.50'",
        atrb2: "Lift top extended height: 41.38'",
        atrb3: "Drawer interior (2) Width : 7.75'",
        atrb4: "Drawer interior (2) Depth : 13.25'",
        atrb5: "Drawer interior (2) Height : 2.50'",
      },
    },
    type: ["Livingroom", "Bedroom", "Diningroom"],
    images: [
      "/Desks/havalance_62_Desk/img1.webp",
      "/Desks/havalance_62_Desk/img2.webp",
      "/Desks/havalance_62_Desk/img3.webp",
      "/Desks/havalance_62_Desk/img4.webp",
    ],
    rating: 4.7,
    discount: "-25%",
    id: "6559c018a7e755f9e0b5c10b",
  },
  {
    _id: "6559c018a7e755f9e0b5c10c",
    name: "Yarlow Lift-Top 36' Home Office Desk",
    price: 200,
    originPrice: 210,
    quantity: 25,
    quantitySale: 8,
    shortDesc: "Home Office Desk",
    fullDesc: {
      data: {
        brief:
          "Elevate your home office with the simply sensational Yarlow lift-top desk. Pairing a dark wood grain look with a black metal base for modern appeal, this minimalistic desk is dressed to impress in a no-muss, no-fuss way. Small storage bins underneath the sleek lift top bring added function.",
        atrb1: "Made of engineered wood and decorative laminate",
        atrb2: "Replicated dark wood grain finish",
        atrb3: "Metal frame with black powder coated finish",
        atrb4: "Lift-top feature; top raises to 39'",
        atrb5: "2 small storage bins under top",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 36.25 -  30.25 -  26.25",
        atrb1: "Chair opening Width : 33.75'",
        atrb2: "Chair opening Depth : 26.25'",
        atrb3: "Chair opening Height : 25.00'",
        atrb4: "Lift top opening (2) Width : 3.75'",
        atrb5: "Lift top opening (2) Depth : 23.00'",
      },
    },
    type: ["Livingroom", "Bedroom", "Diningroom"],
    images: [
      "/Desks/yarlow_Lift_Top_36/img1.webp",
      "/Desks/yarlow_Lift_Top_36/img2.webp",
      "/Desks/yarlow_Lift_Top_36/img3.webp",
      "/Desks/yarlow_Lift_Top_36/img4.webp",
    ],
    rating: 4.7,
    discount: "-5%",
    id: "6559c018a7e755f9e0b5c10c",
  },
  {
    _id: "6559c018a7e755f9e0b5c0f9",
    name: "Wystfield Coffee Table with Lift Top",
    price: 400,
    originPrice: 420,
    quantity: 100,
    quantitySale: 20,
    shortDesc: "Lift Top Coffee Tables",
    fullDesc: {
      data: {
        brief:
          "Double take. Sporting a two-tone finish, dual-sided lid design and expansive storage space, the Wystfield square coffee table takes the art of rustic farmhouse living to a new level. Designer touches include plank-effect styling, heavy distressing and industrial bracket hardware.",
        atrb1: "Made of veneers, wood and engineered wood",
        atrb2: "Distressed finish; vintage white and aged natural pine color",
        atrb3: "Metal bracket hardware",
        atrb4: "2-sided hinged lift top (with stay arms)",
        atrb5: "Assembly required",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 36.00 - 18.00 - 36.00",
        atrb1: "Door opening (2) Width : 31.63'",
        atrb2: "Door opening (2) Depth : 13.50'",
        atrb3: "Door opening (2) Height : 12.88'",
        atrb4: "Weight: 78.00 lbs (35.37 kgs)",
      },
    },
    type: ["Livingroom"],
    images: [
      "/Livingroom/wystfield_Coffee_Table/img1.webp",
      "/Livingroom/wystfield_Coffee_Table/img2.webp",
      "/Livingroom/wystfield_Coffee_Table/img3.webp",
      "/Livingroom/wystfield_Coffee_Table/img4.webp",
    ],
    rating: 4.8,
    discount: "-5%",
    id: "6559c018a7e755f9e0b5c0f9",
  },
  {
    _id: "6559c018a7e755f9e0b5c100",
    name: "Starmore Queen Panel Bed",
    price: 400,
    originPrice: 520,
    quantity: 45,
    quantitySale: 7,
    shortDesc: "Queen Panel Bed",
    fullDesc: {
      data: {
        brief:
          "For fans of urban industrial design, the Starmore queen panel bed clearly steals the show. Its blend of acacia veneer and wood is beautified with an oiled walnut-tone finish for a highly contemporary aesthetic with natural, grainy character. Open plank detailing on the headboard and low-profile footboard perfect the look from head to toe. Mattress and foundation/box spring sold separately.",
        atrb1: "Made of acacia veneers, wood and engineered wood",
        atrb2: "Includes headboard, footboard and rails",
        atrb3: "Foundation/box spring required, sold separately",
        atrb4: "Mattress available, sold separately",
        atrb5: "Assembly required",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 66.25 -  55.00 -  90.25",
        atrb1: "Queen platform rail (2) Width : 79.50'",
        atrb2: "Queen platform rail (2) Depth : 2.25'",
        atrb3: "Queen platform rail (2) Height : 9.50'",
        atrb4: "Panel to floor: 21.75'",
        atrb5: "Queen panel headboard Width : 66.25'",
      },
    },
    type: ["Bedroom"],
    images: [
      "/Bedroom/starmore_Queen_Panel_Bed/img1.webp",
      "/Bedroom/starmore_Queen_Panel_Bed/img2.webp",
      "/Bedroom/starmore_Queen_Panel_Bed/img3.webp",
      "/Bedroom/starmore_Queen_Panel_Bed/img4.webp",
    ],
    rating: 4.9,
    discount: "-30%",
    id: "6559c018a7e755f9e0b5c100",
  },
  {
    _id: "6559c018a7e755f9e0b5c0ff",
    name: "Realyn Queen Upholstered Panel Bed",
    price: 700,
    originPrice: 770,
    quantity: 40,
    quantitySale: 4,
    shortDesc: "Queen Panel Bed",
    fullDesc: {
      data: {
        brief:
          "Elevating the art of traditional cottage styling, the Realyn queen upholstered bed is your dream bedroom retreat realized. A curvaceous beauty, this brilliant upholstered bed wows with dramatic scalloped details and fanciful trim work. The distressed chipped white finish charms with its heirloom appeal. Deep tufting on the cushioned upholstered headboard adds such a cozy element sure to put you at ease. Mattress and foundation/box spring available, sold separately.",
        atrb1:
          "Made of veneers, wood and engineered wood, with cast resin components",
        atrb2: "Includes upholstered headboard, footboard and rails",
        atrb3: "Distressed, chipped white finish",
        atrb4:
          "Polyester upholstered headboard with foam cushion and button tufting",
        atrb5: "Foundation/box spring required, sold separately",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 66.75 -  71.13 - 90.00",
        atrb1: "Queen panel footboard Width : 66.75'",
        atrb2: "Queen panel footboard Depth : 2.75'",
        atrb3: "Queen panel footboard Height : 26.25'",
        atrb4: "Queen upholstered headboard Width : 65.50'",
        atrb5: "Queen upholstered headboard Depth : 3.50'",
      },
    },
    type: ["Bedroom"],
    images: [
      "/Bedroom/realyn_Queen_Upholstered_Panel_Bed/img1.webp",
      "/Bedroom/realyn_Queen_Upholstered_Panel_Bed/img2.webp",
      "/Bedroom/realyn_Queen_Upholstered_Panel_Bed/img3.webp",
      "/Bedroom/realyn_Queen_Upholstered_Panel_Bed/img4.webp",
    ],
    rating: 4.5,
    discount: "-10%",
    id: "6559c018a7e755f9e0b5c0ff",
  },
  {
    _id: "6559c018a7e755f9e0b5c103",
    name: "Realyn 75' Bookcase with 3 Shelves",
    price: 370,
    originPrice: 388.5,
    quantity: 15,
    quantitySale: 2,
    shortDesc: "Bookcase with 3 Shelves",
    fullDesc: {
      data: {
        brief:
          "Elevating the art of traditional cottage styling, the Realyn bookcase is your heavenly home office realized. Antiqued two-tone aesthetic blends a chipped white with a distressed wood tone top for added charm. Clever balance of shelf and drawer space beautifully works.",
        atrb1: "Made of wood, engineered wood and veneers",
        atrb2: "Antiqued two-tone finish",
        atrb3: "Smooth-gliding drawer with dovetail construction",
        atrb4: "3 fixed shelves",
        atrb5: "Dark bronze-tone finished metal hardware",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 45.00 -  74.50 -  16.00",
        atrb1: "Opening #1 Width : 38.00'",
        atrb2: "Opening #1 Depth : 14.50'",
        atrb3: "Opening #1 Height : 13.63'",
        atrb4: "Opening #2 Width : 38.00'",
        atrb5: "Opening #2 Depth : 12.25'",
      },
    },
    type: ["Livingroom", "Bedroom"],
    images: [
      "/Bookcases/realyn_75_Bookcase/img1.webp",
      "/Bookcases/realyn_75_Bookcase/img2.webp",
      "/Bookcases/realyn_75_Bookcase/img3.webp",
      "/Bookcases/realyn_75_Bookcase/img4.webp",
    ],
    rating: 4.9,
    discount: "-5%",
    id: "6559c018a7e755f9e0b5c103",
  },
  {
    _id: "6559c018a7e755f9e0b5c107",
    name: "Kanwyn Large Bookcase with 5 Shelves",
    price: 400,
    originPrice: 440,
    quantity: 41,
    quantitySale: 1,
    shortDesc: "Bookcase with 5 Shelves",
    fullDesc: {
      data: {
        brief:
          "Make a style statement with the Kanwyn large bookcase. Its traditional design is updated with an on trend distressed whitewash finish. The bookcase's five shelves add up to a well-organized workspace.",
        atrb1: "Made with pine wood, veneer and engineered wood",
        atrb2: "Distressed whitewash finish",
        atrb3: "5 shelves; 4 are adjustable",
        atrb4: "Assembly required",
        atrb5: "Estimated Assembly Time: 30 Minutes",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 34.00 -  75.00 -  12.00",
        atrb1: "Opening (2) Width : 29.25'",
        atrb2: "Opening (2) Depth : 10.00'",
        atrb3: "Opening (2) Height : 33.00'",
        atrb4: "Adjustable shelf (4) Width : 32.25'",
        atrb5: "Adjustable shelf (4) Depth : 9.25'",
      },
    },
    type: ["Livingroom", "Bedroom"],
    images: [
      "/Bookcases/kanwyn_Large_Bookcase/img1.webp",
      "/Bookcases/kanwyn_Large_Bookcase/img2.webp",
      "/Bookcases/kanwyn_Large_Bookcase/img3.webp",
      "/Bookcases/kanwyn_Large_Bookcase/img4.webp",
    ],
    rating: 4.9,
    discount: "-10%",
    id: "6559c018a7e755f9e0b5c107",
  },
  {
    _id: "6559c018a7e755f9e0b5c109",
    name: "Aldwin 62' Home Office Lift Top Desk with USB Charging",
    price: 500,
    originPrice: 650,
    quantity: 27,
    quantitySale: 4,
    shortDesc: "Home Office Desk",
    fullDesc: {
      data: {
        brief:
          "Crafted with pine veneers and wood treated to a distressed gray finish, the Aldwin lift top desk is rustic farmhouse living at its best. Crossbuck styling adds striking flair, while metal industrial brackets incorporate an industrial twist. Elevating the functionality of this lift top desk all the more: two smooth-gliding drawers and conveniently placed AC power/USB plug-ins.",
        atrb1: "Made of pine veneers, pine wood and engineered wood",
        atrb2: "Distressed gray finish",
        atrb3: "Metal bracket accents",
        atrb4: "2 smooth-gliding drawers with dovetail construction",
        atrb5: "2 electrical outlets and 2 USB charging ports",
      },
    },
    addInfo: {
      data: {
        dimension: "W-H-D: 60.00 -  31.00 -  28.00",
        atrb1: "Side drawer interior (lined) (2) Width : 9.00'",
        atrb2: "Side drawer interior (lined) (2) Depth : 13.75'",
        atrb3: "Side drawer interior (lined) (2) Height : 2.00'",
        atrb4: "Cord length: 100.00'",
        atrb5: "Lift top opening Width : 20.25'",
      },
    },
    type: ["Livingroom", "Bedroom", "Diningroom"],
    images: [
      "/Desks/aldwin_62_Desk/img1.webp",
      "/Desks/aldwin_62_Desk/img2.webp",
      "/Desks/aldwin_62_Desk/img3.webp",
      "/Desks/aldwin_62_Desk/img4.webp",
    ],
    rating: 4.7,
    discount: "-30%",
    id: "6559c018a7e755f9e0b5c109",
  },
];
